### ISSUE TITLE
minLength error message is missing the path/field that is in error.

### ISSUE THREAD

**Issue by f-unk** [p1c2u/openapi-schema-validator#44]
Given the following OpenAPI schema:

```yaml
model:
      required:
        - email
      type: object
      properties:
        email:
          type: string
          description: Email address of the user
          example: myname@mymail.com
          minLength: 1
```

And given the following input payload to validate against:

```json
{"email": ""}
```

The message returned in the ValidationError looks like:

```
"'' is too short"
```

As you can see, it is missing the field or path that is in error.

P.S.: Thank you for the work on this package. It is very helpful. Any chance we can get multiple errors returned at the same time? :)

Thank you again.
